// ========================================
// DRUG SCRIPT ANALYSIS DEMO — 100% SYNTHETIC DATA
// Weekly prescription counts are generated by a seeded PRNG for three
// invented drugs. The classification rules mirror the real tool
// (ishara-demo scripts.py): maturity-aware thresholds, WoW vs Z-score,
// holiday-excluded baselines.
// ========================================

export type Classification =
  | "Baseline Building"
  | "Meaningfully Below"
  | "Slightly Below"
  | "In-Line"
  | "Slightly Above"
  | "Meaningfully Above";

export interface WeekPoint {
  date: string; // ISO week-ending date
  scripts: number;
  holiday: boolean;
  wow: Classification;
  wowPct: number | null;
  z: Classification;
  zScore: number | null;
}

export interface Maturity {
  stage: string;
  baselineWindow: number;
  inline: number;
  slight: number;
}

export interface Drug {
  id: string;
  name: string;
  blurb: string;
  maturity: Maturity;
  weeks: WeekPoint[];
  agreementPct: number;
}

// Validated diverging palette: blue above · gray in-line · orange below.
// Glyphs on cells provide the required secondary encoding.
export const classMeta: Record<
  Classification,
  { color: string; glyph: string; short: string }
> = {
  "Meaningfully Above": { color: "#164a86", glyph: "▲▲", short: "Meaningful +" },
  "Slightly Above": { color: "#6b9fdd", glyph: "▲", short: "Slight +" },
  "In-Line": { color: "#ccc9c2", glyph: "–", short: "In-line" },
  "Slightly Below": { color: "#d98432", glyph: "▼", short: "Slight −" },
  "Meaningfully Below": { color: "#9c4a10", glyph: "▼▼", short: "Meaningful −" },
  "Baseline Building": { color: "#ffffff", glyph: "·", short: "Baseline" },
};

// Mirrors classify_drug_maturity() in scripts.py
function classifyMaturity(totalWeeks: number): Maturity {
  if (totalWeeks < 26)
    return { stage: "Brand New Release", baselineWindow: 4, inline: 10, slight: 20 };
  if (totalWeeks < 104)
    return { stage: "Emerging / Expanding", baselineWindow: 8, inline: 8, slight: 15 };
  return { stage: "Fully Mature", baselineWindow: 16, inline: 5, slight: 12 };
}

// Mirrors flag_holiday_weeks(): major US holidays, ±3-day buffer
function isHolidayWeek(weekEnd: Date): boolean {
  const targets: [number, number][] = [
    [7, 4], // July 4
    [12, 25], // Christmas
    [1, 1], // New Year
  ];
  for (let d = 0; d < 7; d++) {
    const day = new Date(weekEnd.getTime() - d * 86400000);
    const m = day.getMonth() + 1;
    const dd = day.getDate();
    for (const [tm, td] of targets) if (tm === m && Math.abs(dd - td) <= 1) return true;
    // Thanksgiving: 4th Thursday of November
    if (m === 11 && day.getDay() === 4 && dd >= 22 && dd <= 28) return true;
  }
  return false;
}

// Deterministic PRNG so the demo renders identically on every visit
function lcg(seed: number) {
  let s = seed;
  return () => {
    s = (s * 48271) % 2147483647;
    return s / 2147483647;
  };
}

function genSeries(
  seed: number,
  startISO: string,
  nWeeks: number,
  base: number,
  weeklyGrowth: number,
  noise: number,
  events: Record<number, number> // week index -> multiplicative shock
): { date: string; scripts: number; holiday: boolean }[] {
  const rand = lcg(seed);
  const out: { date: string; scripts: number; holiday: boolean }[] = [];
  let level = base;
  const start = new Date(startISO + "T00:00:00");
  for (let i = 0; i < nWeeks; i++) {
    const weekEnd = new Date(start.getTime() + i * 7 * 86400000);
    const holiday = isHolidayWeek(weekEnd);
    level = level * (1 + weeklyGrowth + (rand() - 0.5) * noise);
    let scripts = level * (events[i] ?? 1);
    if (holiday) scripts *= 0.72 + rand() * 0.1; // holiday dip
    out.push({
      date: weekEnd.toISOString().slice(0, 10),
      scripts: Math.max(1, Math.round(scripts)),
      holiday,
    });
  }
  return out;
}

// Mirrors classify_wow_method + classify_zscore_method
function classify(
  raw: { date: string; scripts: number; holiday: boolean }[],
  m: Maturity
): WeekPoint[] {
  return raw.map((w, i) => {
    // --- WoW ---
    let wow: Classification = "Baseline Building";
    let wowPct: number | null = null;
    if (i > 0) {
      wowPct = ((w.scripts - raw[i - 1].scripts) / raw[i - 1].scripts) * 100;
      const a = Math.abs(wowPct);
      if (a <= m.inline) wow = "In-Line";
      else if (a <= m.slight) wow = wowPct > 0 ? "Slightly Above" : "Slightly Below";
      else wow = wowPct > 0 ? "Meaningfully Above" : "Meaningfully Below";
    }
    // --- Z-score: rolling baseline of prior weeks, holidays excluded ---
    let z: Classification = "Baseline Building";
    let zScore: number | null = null;
    const prior = raw.slice(Math.max(0, i - m.baselineWindow), i).filter((p) => !p.holiday);
    if (i >= m.baselineWindow && prior.length >= 3) {
      const mean = prior.reduce((s, p) => s + p.scripts, 0) / prior.length;
      const sd = Math.sqrt(
        prior.reduce((s, p) => s + (p.scripts - mean) ** 2, 0) / prior.length
      );
      if (sd > 0) {
        zScore = (w.scripts - mean) / sd;
        const a = Math.abs(zScore);
        if (a <= 1) z = "In-Line";
        else if (a <= 2) z = zScore > 0 ? "Slightly Above" : "Slightly Below";
        else z = zScore > 0 ? "Meaningfully Above" : "Meaningfully Below";
      } else z = "In-Line";
    }
    return { ...w, wow, wowPct, z, zScore };
  });
}

function makeDrug(
  id: string,
  name: string,
  blurb: string,
  raw: { date: string; scripts: number; holiday: boolean }[]
): Drug {
  const maturity = classifyMaturity(raw.length);
  const weeks = classify(raw, maturity);
  const scored = weeks.filter(
    (w) => w.wow !== "Baseline Building" && w.z !== "Baseline Building"
  );
  const agree = scored.filter((w) => w.wow === w.z).length;
  return {
    id,
    name,
    blurb,
    maturity,
    weeks,
    agreementPct: scored.length ? Math.round((agree / scored.length) * 100) : 0,
  };
}

export const drugs: Drug[] = [
  makeDrug(
    "alpha",
    "Drug Alpha",
    "Allergy nasal spray · launched 18 weeks ago",
    genSeries(11, "2026-04-10", 18, 240, 0.16, 0.18, { 9: 1.35 })
  ),
  makeDrug(
    "beta",
    "Drug Beta",
    "Cardiology oral · 58 weeks on market",
    genSeries(23, "2025-07-04", 58, 3400, 0.02, 0.1, { 30: 1.28, 44: 0.85 })
  ),
  makeDrug(
    "gamma",
    "Drug Gamma",
    "Mature statin franchise · year 3 post-launch",
    genSeries(37, "2024-05-03", 120, 41000, 0.0005, 0.05, { 70: 0.9, 100: 1.08 })
  ),
];

export function fmtWeek(iso: string): string {
  return new Date(iso + "T00:00:00").toLocaleDateString("en-US", {
    month: "short",
    day: "2-digit",
  });
}
